version: "3.5"

services:
  blog:
    build:
      context: ./
      dockerfile: docker/Dockerfile.local
    image: chestnutfield:local
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      local_network:
        aliases:
          - chestnutfield

networks:
  local_network:
    name: chestnutfield-network
